name: sigea
description: SIGEA – Sistema Institucional de Gestão de Eventos Acadêmicos do IFAL.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.3.0

  # UI / Design
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  glass_kit: ^3.0.0 # Optional, but we will custom build glass widgets too for control
  animations: ^2.0.11

  # State / Utils
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  intl: ^0.19.0
  
  # Biometrics
  local_auth: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    # - assets/images/
